<a href="https://colab.research.google.com/github/bashakamal/Numpy-task_2/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__

'1.21.6'

In [3]:
np.show_config

<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [5]:
x.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [6]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x7f83e5f21210>, toplevel='numpy')>

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [7]:
y=np.zeros(10)
y[4]=1
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [9]:
f=np.arange(10,50)
f[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [11]:
x=[1,2,0,0,4,0]
y=np.nonzero(x)
y

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [12]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [13]:
f=np.random.random((3,3))
f

array([[0.86750594, 0.25441542, 0.52203809],
       [0.90319652, 0.41843627, 0.98585197],
       [0.95105839, 0.68845143, 0.21840771]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [14]:
h=np.random.random((10,10))
print(h.min())
print(h.max())

0.011991150261590033
0.9987471989030798


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [15]:
h=np.random.random(30)
h.mean()

0.5148513881011646

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [16]:
x=np.ones((10,10))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [17]:
x=np.ones((10,10))
y=np.pad(x,pad_width=1)
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [18]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [19]:
x=np.diag([1,2,3,4],k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [20]:
x = np.zeros((8,8),dtype=int)

x[::2,::2] = 1
x[::-2,::-2] = 1
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [21]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [22]:
a=np.zeros((8,8),dtype=int)
a[::2,::2]=1
a[::-2,::-2]=1
np.tile(a,(4,4))

array([[1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       ...,
       [0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [23]:
a=np.random.random((5,5))
max=a.max()
min=a.min()
normalize= a-min/(max-min)
normalize

array([[-0.00250439,  0.22565215,  0.63497873,  0.94541023,  0.099736  ],
       [ 0.57363724,  0.55880025,  0.58009375,  0.46373381,  0.87054961],
       [ 0.02513252,  0.82411471,  0.91322428,  0.65824456,  0.34465096],
       [ 0.17405254,  0.92277892,  0.15579335,  0.70633339,  0.81665863],
       [ 0.92382652,  0.3964668 ,  0.24524216,  0.13252545,  0.20711786]])

In [24]:
a

array([[0.04557798, 0.27373452, 0.6830611 , 0.99349259, 0.14781837],
       [0.6217196 , 0.60688262, 0.62817611, 0.51181618, 0.91863197],
       [0.07321489, 0.87219708, 0.96130664, 0.70632693, 0.39273333],
       [0.22213491, 0.97086128, 0.20387572, 0.75441575, 0.864741  ],
       [0.97190889, 0.44454917, 0.29332453, 0.18060782, 0.25520023]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [25]:
np.dtype

numpy.dtype

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [26]:
a=np.random.random((5,3))
b=np.random.random((3,2))
np.dot(a,b)

array([[0.6519117 , 1.34363752],
       [0.62862995, 1.47063228],
       [0.49441513, 0.92369046],
       [1.02837275, 2.03270343],
       [0.3382939 , 1.02891244]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [27]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a=(s[s<3])
b=(s[s>=8])
con=np.concatenate((a,b))
con

array([0, 1, 2, 8, 9])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [29]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [31]:
s=np.random.random((10))
a=np.round(s)
a

array([1., 1., 1., 1., 1., 0., 0., 0., 1., 0.])

In [32]:
s=np.random.random((10))
a=np.ceil(s)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
s=np.random.random((10))
a=np.abs(s)
a

array([0.40561225, 0.33911354, 0.73256941, 0.22543102, 0.08327208,
       0.93362174, 0.20591093, 0.39221752, 0.24259729, 0.66448744])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [34]:
s=np.array([1,2,3,4,5,6])
f=np.array([2,5,8,4,3])
print(np.intersect1d(s,f)) 

[2 3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [35]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [36]:
np.sqrt(-1) 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [37]:
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [38]:
np.datetime64('today','D')- np.timedelta64(1,'D')

numpy.datetime64('2022-08-19')

In [39]:
np.datetime64('today','D')+ np.timedelta64(1,'D')

numpy.datetime64('2022-08-21')

In [40]:
np.datetime64('today','D')

numpy.datetime64('2022-08-20')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [41]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [42]:
A=3
B=4

In [43]:
A = np.ones(3)*1
B = np.ones(3)*2
# C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [44]:
import numpy as np

In [45]:
s=np.random.random(20)

In [46]:
s

array([0.33957171, 0.83005622, 0.49527752, 0.95457792, 0.66208623,
       0.47377702, 0.39437863, 0.1131562 , 0.46835443, 0.18666201,
       0.50554083, 0.20841736, 0.25343498, 0.10057837, 0.0579103 ,
       0.25232388, 0.11504887, 0.6919568 , 0.93691925, 0.06276979])

In [47]:
np.ceil(s)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [48]:
s.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
np.trunc(s)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [50]:
np.floor(s)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [51]:
a = np.zeros((5,5))
a+= np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [52]:
def generate():
  for n in range(15):
    yield(n) 
Z = np.fromiter(generate(),dtype=float)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [53]:
np.linspace(0,1, num=10, endpoint=True, dtype=None, axis=0)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [54]:
s=np.random.random(10)
s.sort()
s

array([0.03088446, 0.03464633, 0.13513188, 0.19181418, 0.26589218,
       0.76522601, 0.78326715, 0.81170505, 0.86749332, 0.88010793])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [55]:
s=np.arange(5)
np.add.reduce(s)

10

In [56]:
np.sum(s)

10

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [57]:
a=np.random.random(10)
b=np.random.random(10)

In [58]:
np.allclose(a, b)

False

In [59]:
np.array_equal(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [60]:
a=np.random.random(10)
a.flags.writeable

True

In [61]:
a[0]=6
a

array([6.        , 0.88921411, 0.16164493, 0.82780087, 0.58303334,
       0.31357134, 0.68324543, 0.9281587 , 0.63888312, 0.66957371])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [64]:
s=np.random.random(20).reshape(10,2)
s

array([[0.28066864, 0.73264858],
       [0.59953218, 0.65161251],
       [0.87116985, 0.93056978],
       [0.33024232, 0.45855494],
       [0.24115968, 0.86567403],
       [0.75368791, 0.202982  ],
       [0.38723733, 0.63413838],
       [0.86033909, 0.11764867],
       [0.15558357, 0.42592746],
       [0.19408617, 0.70140447]])

In [65]:
np.sqrt(s)

array([[0.52978169, 0.85594894],
       [0.77429463, 0.80722519],
       [0.9333648 , 0.96466045],
       [0.57466713, 0.67716685],
       [0.49108012, 0.93041605],
       [0.86815201, 0.45053523],
       [0.62228396, 0.79632806],
       [0.92754465, 0.34299951],
       [0.39444083, 0.65263118],
       [0.44055212, 0.83749894]])

In [66]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]

np.arctan2(X,Y)

array([0.51613492, 1.43617515, 1.29537386, 1.24728353, 1.04721772,
       0.56649002, 0.36301023, 0.12324961, 0.90139075, 0.87066358])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [67]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
s[s.argmax()]=0

In [69]:
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [70]:
a=np.zeros((5,5))
a,[('x',int),('y',int)]


(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]), [('x', int), ('y', int)])

In [71]:
s = np.zeros((5,5), [('x',int),('y',int)])
s['x']=np.random.random(25).reshape(5,5)
s

array([[(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)]],
      dtype=[('x', '<i8'), ('y', '<i8')])

In [72]:
s['x']=np.arange(25).reshape(5,5)
s['x']

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
s['y']=np.arange(25,50).reshape(5,5)
s['y']

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [74]:
s

array([[( 0, 25), ( 1, 26), ( 2, 27), ( 3, 28), ( 4, 29)],
       [( 5, 30), ( 6, 31), ( 7, 32), ( 8, 33), ( 9, 34)],
       [(10, 35), (11, 36), (12, 37), (13, 38), (14, 39)],
       [(15, 40), (16, 41), (17, 42), (18, 43), (19, 44)],
       [(20, 45), (21, 46), (22, 47), (23, 48), (24, 49)]],
      dtype=[('x', '<i8'), ('y', '<i8')])

In [75]:
s['x'], s['y'] = np.meshgrid(np.linspace(0,26,5),
                             np.linspace(25,51,5))
s

array([[( 0, 25), ( 6, 25), (13, 25), (19, 25), (26, 25)],
       [( 0, 31), ( 6, 31), (13, 31), (19, 31), (26, 31)],
       [( 0, 38), ( 6, 38), (13, 38), (19, 38), (26, 38)],
       [( 0, 44), ( 6, 44), (13, 44), (19, 44), (26, 44)],
       [( 0, 51), ( 6, 51), (13, 51), (19, 51), (26, 51)]],
      dtype=[('x', '<i8'), ('y', '<i8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [76]:
x = np.array([1,2,3,4]) 
y = np.array([5,6,7]) 

In [77]:
c= 1.0 / np.subtract.outer(x,y)


In [78]:
c

array([[-0.25      , -0.2       , -0.16666667],
       [-0.33333333, -0.25      , -0.2       ],
       [-0.5       , -0.33333333, -0.25      ],
       [-1.        , -0.5       , -0.33333333]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [79]:
np.set_printoptions(threshold=3)
np.array([1,2,3,4,5,6])



array([1, 2, 3, 4, 5, 6])

In [80]:
np.set_printoptions(precision=4)
np.array([1.123456789])

array([1.1235])

In [81]:
np.set_printoptions(threshold=3)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [82]:
np.set_printoptions(threshold=3,suppress=True)
Z = np.arange(50)
print(Z)

[ 0  1  2 ... 47 48 49]


In [83]:
eps = np.finfo(float).eps
eps

2.220446049250313e-16

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)













(**hint**: argmin)

In [84]:
Z = np.arange(100)
Z

array([ 0,  1,  2, ..., 97, 98, 99])

In [85]:
Z.argmin()

0

In [86]:
v = np.random.uniform(0,100)
v

7.30866652232629

In [87]:
print(Z-v)

[-7.3087 -6.3087 -5.3087 ... 89.6913 90.6913 91.6913]


In [88]:
np.abs(Z-v)

array([ 7.3087,  6.3087,  5.3087, ..., 89.6913, 90.6913, 91.6913])

In [89]:
a=np.abs(Z-v)
a

array([ 7.3087,  6.3087,  5.3087, ..., 89.6913, 90.6913, 91.6913])

In [90]:
b=a.argmin()
b

7

In [91]:
Z[b]

7

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [92]:
np.array(54)

array(54)

In [93]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [94]:
np.array([[1,2,3,4,5],[1,2,3,4,5]])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [95]:
Z = np.zeros(10, [ ('position', [ ('x', float, 3),
                                  ('y', float, 2)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(([0., 0., 0.], [0., 0.]), (0., 0., 0.))
 (([0., 0., 0.], [0., 0.]), (0., 0., 0.))
 (([0., 0., 0.], [0., 0.]), (0., 0., 0.)) ...
 (([0., 0., 0.], [0., 0.]), (0., 0., 0.))
 (([0., 0., 0.], [0., 0.]), (0., 0., 0.))
 (([0., 0., 0.], [0., 0.]), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [96]:
s=np.random.random(200)
s

array([0.8951, 0.0856, 0.2377, ..., 0.4652, 0.3997, 0.2265])

In [97]:
a=np.atleast_2d(s)
a

array([[0.8951, 0.0856, 0.2377, ..., 0.4652, 0.3997, 0.2265]])

In [98]:
X,Y = np.atleast_2d(a[:,0], a[:,1])
# print(X,Y)
d=X.T

g=Y.T


s1=((X-d)**2)
s2=((Y-g)**2)
f=s1+s2
np.sqrt(f)

array([[0.]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [99]:
s=np.arange(10,dtype=np.float32)
s


array([0., 1., 2., ..., 7., 8., 9.], dtype=float32)

In [100]:
f=s.astype(dtype=np.int32,copy=False)
f

array([0, 1, 2, ..., 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [102]:
from io import StringIO


s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [103]:
z=np.arange(10,20).reshape(5,2)
z

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [104]:
for i, j in np.ndenumerate(z):
    print(i, j)

(0, 0) 10
(0, 1) 11
(1, 0) 12
(1, 1) 13
(2, 0) 14
(2, 1) 15
(3, 0) 16
(3, 1) 17
(4, 0) 18
(4, 1) 19


In [106]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [107]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.3679 0.4482 0.5198 ... 0.5198 0.4482 0.3679]
 [0.4482 0.5461 0.6333 ... 0.6333 0.5461 0.4482]
 [0.5198 0.6333 0.7344 ... 0.7344 0.6333 0.5198]
 ...
 [0.5198 0.6333 0.7344 ... 0.7344 0.6333 0.5198]
 [0.4482 0.5461 0.6333 ... 0.6333 0.5461 0.4482]
 [0.3679 0.4482 0.5198 ... 0.5198 0.4482 0.3679]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [108]:
n=10
p=3

In [109]:
z=np.arange(10,20).reshape(5,2)
z

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [110]:
np.put(z,[2,5,6],[22])


In [111]:
z

array([[10, 11],
       [22, 13],
       [14, 22],
       [22, 17],
       [18, 19]])

In [112]:
np.random.choice(5, 6,6)

array([1, 0, 0, 2, 0, 0])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [113]:
a=np.arange(50).reshape(5,10)
a

array([[ 0,  1,  2, ...,  7,  8,  9],
       [10, 11, 12, ..., 17, 18, 19],
       [20, 21, 22, ..., 27, 28, 29],
       [30, 31, 32, ..., 37, 38, 39],
       [40, 41, 42, ..., 47, 48, 49]])

In [114]:
np.mean(a)

24.5

In [115]:
x=np.mean(a,axis=1,keepdims=True)
x

array([[ 4.5],
       [14.5],
       [24.5],
       [34.5],
       [44.5]])

In [116]:
np.subtract(a,x)

array([[-4.5, -3.5, -2.5, ...,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, ...,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, ...,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, ...,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, ...,  2.5,  3.5,  4.5]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [117]:
a=np.random.random(15).reshape(5,3)
a

array([[0.5365, 0.9511, 0.6803],
       [0.0104, 0.2739, 0.9942],
       [0.5209, 0.0945, 0.3013],
       [0.3637, 0.0771, 0.4149],
       [0.3166, 0.121 , 0.8452]])

In [118]:
a[a[:,2].argsort()]

array([[0.5209, 0.0945, 0.3013],
       [0.3637, 0.0771, 0.4149],
       [0.5365, 0.9511, 0.6803],
       [0.3166, 0.121 , 0.8452],
       [0.0104, 0.2739, 0.9942]])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [119]:
a=np.random.random(10)
a

array([0.2733, 0.635 , 0.0473, ..., 0.0686, 0.3715, 0.2827])

In [120]:
print((~a.any(axis=0).any()))


False


In [121]:
s=(~a.any(axis=0).any())
s

False

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [122]:
a=[np.arange(5,35)]
s=np.array(a)
s.argmin()


0

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [123]:
a=[1,2,3]
b=[4,5,6]
s=np.array(a).reshape(1,3)
print(s)
f=np.array(b).reshape(3,1)
print(f)


[[1 2 3]]
[[4]
 [5]
 [6]]


In [124]:
g=np.nditer([s,f,None])
for x,y,z in g:
  z[...]=x+y
print(g.operands[2])

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [125]:
for x,y in np.nditer([s,f]):
  print(x+y)

5
6
7
6
7
8
7
8
9


In [126]:
def iter_add_py(x, y, out=None):
    addop = np.add
    it = np.nditer([x, y, out], [],
                [['readonly'], ['readonly'], ['writeonly','allocate']])
    with it:
        for (a, b, c) in it:
            addop(a, b, out=c)
        return it.operands[2]


In [127]:
a=[1,2,3]
b=[4,5,6]
x=np.array(a).reshape(1,3)
y=np.array(b).reshape(3,1)

In [128]:
iter_add_py(x, y, out=None)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [130]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[3. 4. 2. ... 1. 1. 4.]
[5. 7. 3. ... 1. 1. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [131]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. ... 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [132]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [133]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[49 57 49 48]
 [61 47 57 68]
 [49 39 55 61]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [134]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.5415 0.4859 0.312  ... 0.4647 0.411  0.6377]
0    0.541514
1    0.485859
2    0.312003
3    0.511721
4    0.424363
5    0.257233
6    0.427257
7    0.464704
8    0.411028
9    0.637665
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [135]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

np.sum(A * B.T, axis=1)

np.einsum("ij,ji->i", A, B)

array([1.274 , 1.4914, 1.5013, 1.0414, 0.3211])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [136]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. ... 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [137]:
A = np.ones((5,5,3))
print(A)
B = 2*np.ones((5,5))
print(B)
# print(A * B)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [138]:
print(A*B[:,:, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [139]:
A = np.arange(20).reshape(10,2)
A

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       ...,
       [14, 15],
       [16, 17],
       [18, 19]])

In [140]:
A[[0,5]]=A[[1,6]]
print(A)

[[ 2  3]
 [ 2  3]
 [ 4  5]
 ...
 [14 15]
 [16 17]
 [18 19]]


In [141]:
A[[0,5]]

array([[ 2,  3],
       [12, 13]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [154]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(10, 22) (10, 87) (11, 48) ... (59, 89) (63, 75) (64, 89)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [155]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 ... 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [156]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))



from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3. ... 16. 17. 18.]
[ 1.  2.  3. ... 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [157]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 ...
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 ...
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [158]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.1101,  0.9438,  0.9411, ...,  0.1003, -0.7562, -0.7462])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [159]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 6.5265  8.8162  2.4942 ... 15.5639  5.2605  2.2776]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [141]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [160]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 6 6 ... 9 9 8]
 [8 8 4 ... 2 3 3]
 [5 8 3 ... 7 7 1]
 ...
 [8 6 6 ... 6 0 6]
 [4 5 5 ... 5 7 0]
 [2 7 6 ... 1 1 3]]
[[0 0 0 0 0]
 [0 5 6 6 7]
 [0 8 8 4 5]
 [0 5 8 3 7]
 [0 1 2 6 2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [161]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)



Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 ...
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 ...
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [163]:
 Z= np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)


rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [142]:
a=np.random.randint(2,8,10)
a

array([2, 6, 5, ..., 2, 4, 4])

In [143]:
np.bincount(a)

array([0, 0, 3, ..., 3, 2, 1])

In [144]:
a.argmax()

1

In [145]:
(np.bincount(a).argmax())

2

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [164]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[0 2 0]
   [1 3 1]
   [0 4 4]]

  [[2 0 1]
   [3 1 1]
   [4 4 0]]

  [[0 1 2]
   [1 1 0]
   [4 0 2]]

  ...

  [[4 1 0]
   [0 1 4]
   [3 4 3]]

  [[1 0 1]
   [1 4 3]
   [4 3 4]]

  [[0 1 2]
   [4 3 0]
   [3 4 2]]]


 [[[1 3 1]
   [0 4 4]
   [1 2 2]]

  [[3 1 1]
   [4 4 0]
   [2 2 1]]

  [[1 1 0]
   [4 0 2]
   [2 1 1]]

  ...

  [[0 1 4]
   [3 4 3]
   [4 1 3]]

  [[1 4 3]
   [4 3 4]
   [1 3 0]]

  [[4 3 0]
   [3 4 2]
   [3 0 1]]]


 [[[0 4 4]
   [1 2 2]
   [1 3 1]]

  [[4 4 0]
   [2 2 1]
   [3 1 2]]

  [[4 0 2]
   [2 1 1]
   [1 2 3]]

  ...

  [[3 4 3]
   [4 1 3]
   [0 4 4]]

  [[4 3 4]
   [1 3 0]
   [4 4 0]]

  [[3 4 2]
   [3 0 1]
   [4 0 0]]]


 ...


 [[[3 0 2]
   [0 4 2]
   [1 0 2]]

  [[0 2 3]
   [4 2 2]
   [0 2 2]]

  [[2 3 0]
   [2 2 2]
   [2 2 0]]

  ...

  [[0 1 0]
   [3 0 4]
   [2 1 3]]

  [[1 0 0]
   [0 4 3]
   [1 3 1]]

  [[0 0 1]
   [4 3 2]
   [3 1 1]]]


 [[[0 4 2]
   [1 0 2]
   [3 4 2]]

  [[4 2 2]
   [0 2 2]
   [4 2 0]]

  [[2 2 2]
   [2 2 0]
   [2 0 4]]

  ...

  [[3

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [165]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3 10 11 15 12]
 [10  0 10 17  6]
 [11 10  8 42 16]
 [15 17 42  0  7]
 [12  6 16  7  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [166]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 ...
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [167]:
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))


Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[28 40 12]
 [39 33 14]
 [22  7  9]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [168]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [169]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9996 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [170]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 ...
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [146]:
import numpy as np

In [147]:
a=np.random.random(20)
a

array([0.2987, 0.8502, 0.4251, ..., 0.2319, 0.9921, 0.6098])

In [148]:
np.core.records.fromarrays(a)

rec.array((0.2987, 0.8502, 0.4251, 0.5589, 0.6274, 0.8497, 0.5291, 0.6147, 0.404, 0.1652, 0.0457, 0.3432, 0.1016, 0.2897, 0.7646, 0.1757, 0.9482, 0.2319, 0.9921, 0.6098),
          dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', '<f8'), ('f5', '<f8'), ('f6', '<f8'), ('f7', '<f8'), ('f8', '<f8'), ('f9', '<f8'), ('f10', '<f8'), ('f11', '<f8'), ('f12', '<f8'), ('f13', '<f8'), ('f14', '<f8'), ('f15', '<f8'), ('f16', '<f8'), ('f17', '<f8'), ('f18', '<f8'), ('f19', '<f8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [149]:
a=np.random.randint(5,10,20)
a

array([9, 5, 6, ..., 7, 9, 6])

In [150]:
np.power(a,3)

array([729, 125, 216, ..., 343, 729, 216])

In [151]:
a**3

array([729, 125, 216, ..., 343, 729, 216])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [152]:
A=np.random.randint(5,18,24).reshape(8,3)
b=np.random.randint(5,9,4).reshape(2,2)
print(A)
print(b)

[[ 6 14 17]
 [12  9  8]
 [12 16  5]
 ...
 [15 17 16]
 [ 5 16  5]
 [11 17  7]]
[[7 6]
 [5 8]]


In [171]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 ... 4 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [172]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 0 4]
 [1 3 1]
 [4 0 1]
 ...
 [0 4 4]
 [0 3 4]
 [1 4 0]]
[[0 0 4]
 [1 3 1]
 [4 0 1]
 ...
 [0 4 4]
 [0 3 4]
 [1 4 0]]
[[0 0 4]
 [1 3 1]
 [4 0 1]
 ...
 [0 4 4]
 [0 3 4]
 [1 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [174]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [175]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]
[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [176]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)      
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)  

array([[0.5035, 0.3492, 0.0621, ..., 0.4343, 0.3626, 0.3894],
       [0.8173, 0.5669, 0.1008, ..., 0.705 , 0.5885, 0.6321],
       [0.0672, 0.0466, 0.0083, ..., 0.058 , 0.0484, 0.052 ],
       ...,
       [0.2216, 0.1537, 0.0273, ..., 0.1911, 0.1595, 0.1714],
       [0.6969, 0.4833, 0.0859, ..., 0.6011, 0.5018, 0.5389],
       [0.6675, 0.4629, 0.0823, ..., 0.5758, 0.4806, 0.5162]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [180]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [178]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [179]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.1815  0.1763]
